### ISSUE TITLE
Username Fill Often Missing

### ISSUE THREAD

**Issue by sjug** [nwallace/passff#110]
Hello there,

I have been a long time pass user, very happy to see a firefox addon!
I'm just getting up and running with it, but it seems that I'm having issues with the username/user/login form value being populated.

I follow the correct field format in my password repository and it works for some websites, however, others PassFF doesn't fill the field on the website.

For example: https://app.tutanota.de/

edit:
Just reviewed the code and it's because of the input.name missmatch with PassFF.Preferences.loginInputNames

Can we suggest additional values for that preference?

edit2:
Another example of the same issue:
https://news.ycombinator.com/login?goto=news

I'm not sure if the input.name matching is going to work. I'll see if there's another way to find login inputs.

**Comment by sometoby** [comment]
Of course, PR's and suggestions for new field names to match are always welcome.

**Comment by shtrom** [comment]
There's also the issue of sites purposefully renaming their login field with a random value, for some reason.

**Comment by tuxor1337** [comment]
Since `PassFF.Preferences.loginInputNames` can be changed in the preferences, I regard this issue as fixed.
