### ISSUE TITLE
Pass doesn't like GPG-Smartcards

### ISSUE THREAD

**Issue by WilhelmErasmus** [nwallace/passff#126]
When using a GPG smartcard that works fine with the command-line version of pass, passff doesn't work. It seems to not wit long enough to complete pin entry.
Error: 

> Can't access to your password.
> Please add your passphrase to gpg-agent first.

**Comment by phryneas** [comment]
* are you using pgp version 2.0 or 2.1?
* can you test the "through shell" method? (arguments `-l -i`)

**Comment by WilhelmErasmus** [comment]
It actually seems to be working now. I think the timeout may be a bit short, because I still get errors relating to the gpg-agent not being ready if I have not yet entered my pin or if I have not authenticated the transaction on-token within a few seconds(timeout in pass comman line interface is 15 seconds).

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
