### ISSUE TITLE
Arrow keys (up/down) do not move selection in popup menu

### ISSUE THREAD

**Issue by craftyguy** [nwallace/passff#130]
When the popup menu is displayed (such as using the shortcut to display it), the keyboard up and down arrow keys do not move the selection through the available leaf items in the list. Well, more accurately, if you hit the down arrow it moves the selection down once but no more. The up arrow seems to have no effect. With logging enabled, I see that PassFF is registering the key presses, but control seems to transfer back to the webpage since it scrolls up/down depending on which key is pressed.

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
