### ISSUE TITLE
Multiple window “breaks” the addon

### ISSUE THREAD

**Issue by gui-don** [nwallace/passff#131]
PassFF only seems to work in Firefox main window.

If I open multiple windows (private or not), I cannot navigate through my password as the passff little GUI seems to be frozen.

It only concerns newly opened windows, passFF still works in the main window.

On every version of Firefox, Archlinux.

(May be related to [issue #94](https://github.com/jvenant/passff/issues/94))

**Comment by jvenant** [comment]
We are working on an new plugin design that I hope will solve this kind of issues

**Comment by gui-don** [comment]
Great! Keep up the good work.

**Comment by craftyguy** [comment]
@jvenant Do you happen to have the code for the new design posted somewhere? I'm curious :)

**Comment by jvenant** [comment]
Of course. It's on the addon-sdk branch.
Mainly design by @sometoby but not working yet.
I'm working on it, but unfortunatly don't have lot of time for it

**Comment by shtrom** [comment]
:+1:

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
