### ISSUE TITLE
Miss PassFF when Firefox reboot

### ISSUE THREAD

**Issue by Mitchou** [nwallace/passff#137]
When I install new plugin in Firefox and need to restart it, after I won't get PassFF icon.
So I can't use it until I close and relauch Firefox.

Firefox 44.0.2 (Fedora 23 x64)
PassFF 0.1.29

**Comment by jvenant** [comment]
Could be the same bug than #93

**Comment by terlar** [comment]
I also think I have this issue, I always thought PassFF was randomly uninstalled now and then. But perhaps it is just the shortcut and icon that is gone?

**Comment by ainola** [comment]
Same here! I need to disable/reenable the addon to get it to appear again.

**Comment by robinvd** [comment]
I only had this on firefox nighly. Disabling and enabling the addon fixed it

**Comment by Thor77** [comment]
Can still reproduce with Nightly 54.0a1 on ArchLinux.
It doesn't disappear on every restart, though just sometimes...

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
