### ISSUE TITLE
password prompt delayed on ubuntu 15.10 with FF45

### ISSUE THREAD

**Issue by srccon** [nwallace/passff#141]
Love the plugin, only issue is that it take 15-20 seconds for the gnupg password prompt to come up when trying to retrieve a passcode. What could be causing the delay?

PassFF 0.1.30

**Comment by jvenant** [comment]
Have no idea...
* Do you have the same behavior using pass script from a shell or older versions of PassFF ?
* Do you use an usb key to store your password ?
* Does this happen only the first time gnupg agent prompt for the password
* Could you try using both "through shell" and "direct call method"

**Comment by srccon** [comment]
Your ready for this. It only happens when I start up my computer connected to a second monitor...yeah...

I have not used previous versions of PassFF. There is no lag when invoking from command line or QTpass, regardless of whether or not the system was started with the second monitor. 

The .password-store is in the $HOME directory, not on an external. 

It happens ever time when invoked by when the computer is booted connected to the external monitor, but does not happen when the computer is connected to the second monitor after booting (I have a laptop dock). 

So weird.

**Comment by 0x1f415** [comment]
having the same issue here. same conditions as @srccon, except I have a desktop with only one monitor.

**Comment by srccon** [comment]
Waaa? @0x1f415 that's not working for me, I get:

`gpg-connect-agent: can't connect to the agent: IPC connect call failed`

It's never happened for me in anything other than FF. Shell and qtpass have always been instant. 

@0x1f415 thanks for validating that its not just me! 

@jvenant Love the plugin even with the delay. Any thoughts on what is causing it?

**Comment by 0x1f415** [comment]
```
[PassFF] copy to clipboard click { target: <richlistitem#passff-menu-richlistitem5>, buttons: 0, clientX: 1150, clientY: 279, layerX: 190, layerY: 125 } bootstrap.js:37
[PassFF] Execute pass Object { command: "/usr/bin/pass", arguments: Array[1], environment: Array[7], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executePass/params.done() } bootstrap.js:37
[PassFF] [subprocess] getlimit: maxFD=1024
[PassFF] [subprocess] subprocess started; got PID 25332
[PassFF] [subprocess] trying to close stdin
[PassFF] [subprocess] Closing Stdin
[PassFF] [subprocess] Got msg from stdout: initialising library with libc.so.6
[PassFF] [subprocess] Got msg from stderr: initialising library with libc.so.6
[PassFF] [subprocess] got 134 bytes from stdout
[PassFF] [subprocess] Got msg from stdout: poll returned HUP
[PassFF] [subprocess] Got msg from stderr: poll returned HUP
[PassFF] [subprocess] Pipe stderr closed
[PassFF] [subprocess] got 0 bytes from stdout
[PassFF] [subprocess] Pipe stdout closed
[PassFF] [subprocess] Cleanup called
[PassFF] [subprocess] trying to close stdin
[PassFF] pass script execution ok bootstrap.js:37
```

**Comment by 0x1f415** [comment]
I found a fix! and it has nothing to do with passff!

the solution was in the very beginning of `gpg-agent`'s man page:

> The usual way to run the agent is from the ~/.xsession file:
> 
> `eval $(gpg-agent --daemon)`
> 
> If you don't use an X server, you can also put this into your regular startup file ~/.profile or .bash_profile.  It is best not to  run  multiple
> instance  of  the gpg-agent, so you should make sure that only one is running: gpg-agent uses an environment variable to inform clients about the
> communication parameters. You can write the content of this environment variable to a file so that you can test for a running agent.  Here is  an
> example using Bourne shell syntax:
> 
>  ```gpg-agent --daemon --enable-ssh-support \
> 		   --write-env-file "${HOME}/.gpg-agent-info"```
> 
> This  code  should only be run once per user session to initially fire up the agent.  In the example the optional support for the included Secure
> Shell agent is enabled and the information about the agent is written to a file in the HOME directory.  Note that by  running  gpg-agent  without
> arguments you may test whether an agent is already running; however such a test may lead to a race condition, thus it is not suggested.
> 
> The second script needs to be run for each interactive session:
> 
> ```
>  if [ -f "${HOME}/.gpg-agent-info" ]; then
>    . "${HOME}/.gpg-agent-info"
>    export GPG_AGENT_INFO
>    export SSH_AUTH_SOCK
>  fi
> ```

**Comment by jvenant** [comment]
Thank you very much for your feedback.
I'll add an entry in the faq about this

**Comment by srccon** [comment]
Excellent, added to my startup applications(gnome) and startup script (xmonad).
