### ISSUE TITLE
Overwrites preferences with defaults

### ISSUE THREAD

**Issue by tasmo** [nwallace/passff#144]
In Firefox beta on latest Mac OS X **passff** overwrites my preferences with default parameters. This does after every quitting and new starting a new Firefox session.
I have installed `pass` and `bash` with homebrew so the paths are located in `/usr/local/bin`. The reset to the default parameters curses the following error message of **passff**:

> Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.isExecutable]

**Comment by jvenant** [comment]
Which version of passff are you using exactly ?

**Comment by tasmo** [comment]
PassFF 0.1.30 and Firefox 46.0b9

**Comment by jvenant** [comment]
Did you try with FireFox 45 ?

**Comment by Philelis** [comment]
Yeah I had the same problem today with Firefox 45.0.1, but I had it only once. After changing the paths it works, even after restarting Firefox.
PassFF 0.1.29

**Comment by mbretter** [comment]
Same problem, from time to time, settings are reset to defaults.
FF 45.0.2, PassFF 0.1.30

**Comment by timatlee** [comment]
Same here, FF 47 on Windows 7 x64, using paths pointing at Cygwin.
PassFF 0.1.31.

Also, might be the same as #152 ?

**Comment by rettgerst** [comment]
https://github.com/jvenant/passff/issues/152#issuecomment-244466258

**Comment by fdw** [comment]
I also have the problem that my settings are being overwritten with the default values. I cannot see a pattern as to when, unfortunately.

What information do you need?

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
