### ISSUE TITLE
Data organisation by line number

### ISSUE THREAD

**Issue by tastytea** [nwallace/passff#145]
Hi,
I don't like pre-pending "login:" or anything before my username. I just write my password in line 1 and my username in line 2. Currently passff uses the filename as username when auto-filling.
Could you add an option to tell passff in which line the username is, please?

**Comment by gutierri** [comment]
@tastytea Add an option for "login" to be able to have another name? I did not understand the problem

**Comment by tuxor1337** [comment]
We could add the feature that if no items with colon (:) have been found, the second line is assumed to be the login name. Would that solve this issue for everyone?

**Comment by gutierri** [comment]
this seems like a good solution...16.04.2017, 08:59, "Thomas Vogt" <notifications@github.com>:We could add the feature that if no items with colon (:) have been found, the second line is assumed to be the login name. Would that solve this issue for everyone?

**Comment by tastytea** [comment]
Yes, that's what I meant.
