### ISSUE TITLE
autocomplete on page browse gets permissions error

### ISSUE THREAD

**Issue by draconicfae** [nwallace/passff#150]
When I browse to a page where autocomplete should happen I get 

ObjectActor.prototype.grip previewer function threw an exception: Error: Permission denied to access object
Stack: PseudoArray@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/object.js:1452:16
ObjectActor.prototype.grip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/object.js:121:15
WCA_objectGrip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:461:12
createValueGrip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/object.js:1851:1
WCA_createValueGrip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:409:12
WCA_objectGrip/actor<.createValueGrip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:454:29
DOMEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/object.js:1419:1
ObjectActor.prototype.grip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/object.js:121:15
WCA_objectGrip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:461:12
createValueGrip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/object.js:1851:1
WCA_createValueGrip@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:409:12
WCA_prepareConsoleMessageForRemote/result.arguments<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:1458:14
WCA_prepareConsoleMessageForRemote@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:1456:24
WCA_onConsoleAPICall@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/webconsole.js:1300:16
CAL_observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/toolkit/webconsole/utils.js:1467:5
CS_recordEvent@resource://gre/components/ConsoleAPIStorage.js:134:5
sendConsoleAPIMessage@resource://gre/modules/devtools/Console.jsm:566:5
createMultiLineDumper/<@resource://gre/modules/devtools/Console.jsm:496:5
logPrototype@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/myusername/.mozilla/firefox/ojmchiw1.default/extensions/passff@invicem.pro.xpi!/bootstrap.js:37:7
PassFF.windowListener.onWebPageLoaded@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/myusername/.mozilla/firefox/ojmchiw1.default/extensions/passff@invicem.pro.xpi!/bootstrap.js:301:1
Line: 0, column: 0 DevToolsUtils.js:59:0

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
