### ISSUE TITLE
settings resetting at browser restart

### ISSUE THREAD

**Issue by phryneas** [nwallace/passff#152]
This occured first as we were investigating #151, but is now happening for me as well (FF 46.0.1).
After a browser restart, passff settings are reverted to default settings - hence passff stops working on every browser restart.
Unfortunately, at that moment no logging is available as the "loggin"-options is reset as well.

**Comment by phryneas** [comment]
this seems to originate in https://github.com/jvenant/passff/blob/master/src/modules/preferences.js around line 40, as that loop seems to be only executing for 
`
[PassFF] aaaaa  iframeSearchDepth 5
[PassFF] aaaaa  callType direct
[PassFF] aaaaa  caseInsensitiveSearch false
[PassFF] aaaaa  enterBehavior 0
[PassFF] aaaaa 
`
and then stops without reading any further prefences.

I may check this in the next few days when I find the time for it, but no guarantees.

**Comment by phryneas** [comment]
this might somehow be related to b67a4ef

**Comment by phryneas** [comment]
hmm... the incomplete log above can be explained by the logging variable to be initialized only that late. but that's it :/

**Comment by timatlee** [comment]
Same here..  FF 47.0 on Windows 7 x64.  I can post more logging, if I can figure out how, and if it would add value.

**Comment by phryneas** [comment]
Unfortunately, the bug disappeared while testing it and hasn't reappeared since then for me.

I was testing this branch: https://github.com/phryneas/passff/commits/Issue152 - there should be nothing in there that resolves it, but you are free to give the current HEAD a try, maybe it works for you ^^

**Comment by timatlee** [comment]
Yeah, I'm having a hard time finding the specific steps to reproduce the bug.

The only thing I can figure out is that if there is a path error at all, it seems as though settings aren't saved.

So, if I have passFF configured, and hit Refresh, the password store loads.  I exit FF, relaunch, and passFF is still configured.

However, if I have passFF configured, and change the mode from "Direct Call" to "Through Shell", and then refresh the password store, I get a path error.  Go back into the settings, set it back to Direct Call (which was working), refresh, no path error.  Exit FF, re-launch, and I will have settings reset.

I'll try your branch in a bit.

**Comment by timatlee** [comment]
Ok..  So, I poked around with it this morning, and I think there's something to the case where an error gets generated, and settings get reset.  Using the Issue152 branch, I can make the preferences get reset/revert to default by:

2. Launch firefox
3. Set user home (c:\\users\\tima)
4. Set pass command (c:\\cygwin64\\bin\\bash.exe)
5. Set arguments (--login /usr/bin/pass)
6. leave the Script Call Method as Direct Call
7. Test things out, passwords load, populate, etc.
8. Switch Script Call method to Through Shell.  Hit OK on pref's.
9. Refresh the password, get a path error.
10. Switch Script Call Method to Direct Call
11. Refresh password, get a path error.
12. Switch Script Call Method to Direct Call ..  again.
13. Refresh password, success.
14. "simple" test ..  recognize that I'm at Github, can load password, etc.
15. Exit Firefox
16. Re-launch Firefox, path error, preferences are empty.

The path error I get is:
Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]

It generally reminds me that the path to the Pass Command is not valid.  Once that parameter is set, the error dialog goes away.

**Comment by mcnesium** [comment]
For some reason I created a new firefox profile for my daily usage a couple of weeks ago and had not installed passff again yet. By the time FF had been updated to v47 and one day I felt like trying this plugin again. So I installed it and it worked fine for some days of usage. Then the FF update to v47.0.1 came in and since the day the passff plugin started bugging me again. It's all the same symptoms described here and in #151. Just to let you know…

**Comment by rettgerst** [comment]
for those still suffering with this problem, you can create a user.js file in the root of your profile folder to force the settings. mine looks like this:

```javascript
user_pref("extensions.passff.caseInsensitiveSearch", true);
user_pref("extensions.passff.command", '/usr/bin/pass');
user_pref("extensions.passff.shell", 'C:\\\\msys64\\\\usr\\\\bin\\\\bash.exe');
user_pref("extensions.passff.shellArgs", '--login');
user_pref("extensions.passff.enterBehavior", 1);
user_pref("extensions.passff.callType", 'shell');
```

yes, you need to escape back-slashes twice.

**Comment by timatlee** [comment]
Upvote?  Gold?  I'm not sure how to send a github "Thank you".  But thank
you!

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
