### ISSUE TITLE
passff crashes on startup

### ISSUE THREAD

**Issue by ihavenoface** [nwallace/passff#153]
For me passff crashes on every new startup of the browser with the following error message:

```
addons.manager  WARN    Exception calling callback: TypeError: doc.getElementById(...) is null (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/noface/.mozilla/firefox/cq5hegtk.default/extensions/passff@invicem.pro.xpi!/bootstrap.js:209:7) JS Stack trace: PassFF.windowListener.addUI@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/noface/.mozilla/firefox/cq5hegtk.default/extensions/passff@bootstrap.js:209:7 < PassFF.waitForDocuments@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/noface/.mozilla/firefox/cq5hegtk.default/extensions/passff@bootstrap.js:129:9 < PassFF.init@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/noface/.mozilla/firefox/cq5hegtk.default/extensions/passff@bootstrap.js:111:5 < startup/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/noface/.mozilla/firefox/cq5hegtk.default/extensions/passff@bootstrap.js:69:3 < safeCall@AddonManager.jsm:179:5 < makeSafe/<@AddonManager.jsm:195:25 < Handler.prototype.process@Promise-backend.js:933:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:812:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:746:11
```

Disabling and reenabling the extension usually fixes it.

**Comment by ihavenoface** [comment]
Turns out the root of the issue was the extension called [Self-Destructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/).

**Comment by jvenant** [comment]
I've just received an email saying : 
"Turns out the root of the issue was the extension called Self-Destructing Cookies."
But can't see the message in the comment.
Can you confirm ?

**Comment by ihavenoface** [comment]
I removed the comment since the issue popped up again after testing with Self-Destructing Cookies dis/enabled.
It might just be something with my setup but I'm unsure what could cause it after all.

**Comment by Stebalien** [comment]
I'm seeing the same issue. I also have self-destructing cookies but it seems unlikely to be causing the problem. This looks like a race condition. Firefox doesn't seem to wait for addons buttons to finish loading before declaring the window dom ready.

**Comment by tuxor1337** [comment]
Please reopen if this still applies with latest version from Github.
