### ISSUE TITLE
Doesn't support unicode names

### ISSUE THREAD

**Issue by Forever-Young** [nwallace/passff#165]
Displays them like '\322\207...'

**Comment by jvenant** [comment]
Usually this is a issue with your environment.
Do you use direct call or through shell method ?

**Comment by Forever-Young** [comment]
Tried both method, the same

Locale is en_US.UTF-8

```
$ pass ls
[SNIP]
├── тест
│   └── тест
└── тест
```
But in browser: [photo](https://goo.gl/photos/NRixchFQJQD3tm2r8)

**Comment by jvenant** [comment]
did you set the shell arguments to `--login` ?

**Comment by Forever-Young** [comment]
Thanks, that helped.

Why this is not default?

**Comment by jvenant** [comment]
Cool.
Because it is slower and not necessarily required.
But there is a note about `--login` in the documentation.

**Comment by Forever-Young** [comment]
Yes, but it's about OS X problems, I'm using Linux.

**Comment by jvenant** [comment]
You're right. I'm going to clarify that. Thank you very much

**Comment by tuxor1337** [comment]
Please reopen, if this still applies for the latest version in Github.
