### ISSUE TITLE
Project ownership

### ISSUE THREAD

**Issue by jvenant** [nwallace/passff#170]
Hi everybody,

Because I don't have enough time to continue developing on passff and bring it to the next stage, I'm going to transfert the ownership of the project to @nwallace.
I think the community expectations are strong on passff, and I'm sure Nathan will be able to answer them and continue to improve the addon. I'll still keep an eye on the project and maybe do some pull requests from time to time.
I'm very happy with the success of passff (and of course of pass). it was a very good experience for me.
You are an awesome community !

Johan

**Comment by nwallace** [comment]
Thanks @jvenant for all the effort to create this project and get it to where it is today.  I love this add-on, so I'm honored and excited to take over ownership.  I want this to remain a real community project, so I hope everyone will stay involved :smile:

Please reach out to me if you have any thoughts or suggestions for the future of this project.

Cheers to Johan's great work and leadership :champagne:
