### ISSUE TITLE
'Display' doesn't show all info

### ISSUE THREAD

**Issue by Forever-Young** [nwallace/passff#173]
I have:
> __password__
> Login: aaabbb
> Url: http://aaa.com
in my file, Display shows only password and login, but no url

**Comment by nwallace** [comment]
Thanks for the idea. I agree we should show the URL. I wonder, should we try to show the entire file too? For me personally, that would be good, but I wonder if anyone has any reason that would be undesirable -- maybe we should just stick to displaying information the extension is going to use?

**Comment by Forever-Young** [comment]
Why not? :)
