### ISSUE TITLE
Display Contextual doesn't display contextual entries

### ISSUE THREAD

**Issue by bonds** [nwallace/passff#176]
My password store is organized into the recommended format, i.e.

````
~ ❯❯❯ pass search github.com
Search Terms: github.com
└── github.com
    ├── login
    ├── password
    └── url
~ ❯❯❯
````

Yet, when I use the passff addon in Firefox and press the "(P)" icon, I see the wrong entries by default and I see those same entries after pressing the 'Display contextual' button:

![2016-11-27-081837_1280x800_scrot](https://cloud.githubusercontent.com/assets/53434/20649762/77d783ba-b47b-11e6-9009-a32781147ae8.png)

I can search for what I expected it to display (in this example, 'github.com') and find it just fine:

![2016-11-27-081852_1280x800_scrot](https://cloud.githubusercontent.com/assets/53434/20649766/95d0a612-b47b-11e6-9dab-ab742a3a6de0.png)

So, it appears that something is wrong with the 'Display contextual' feature.

Let me know if I can help by grabbing logs and posting them here. I did a little poking around in that regard but haven't been able to figure out the issue as yet.

**Comment by varac** [comment]
Same for me.

**Comment by nwallace** [comment]
Thanks for the info.

This issue stems from the current "search" implementation, which is being discussed here https://github.com/nwallace/passff/issues/127. I'm hoping to make some improvements in this area in the coming month or two. I'm going to close this issue as a duplicate, but please continue the conversation on the other issue if you have more to ask or add.
