### ISSUE TITLE
DBUS_SESSION_BUS_ADDRESS environment variable

### ISSUE THREAD

**Issue by davidar** [nwallace/passff#186]
I've been getting the same error as #100 and I think I've narrowed the problem down to the fact that passff isn't passing through the `DBUS_SESSION_BUS_ADDRESS` environment variable - for some reason gpg-agent is refusing to operate without this. Is there a whitelist somewhere that this could be added to?

**Comment by tuxor1337** [comment]
Have you tried to reproduce your issue using the latest version from Github?

**Comment by davidar** [comment]
Ah, seems to be fixed in master :)
