### ISSUE TITLE
Where can I download the install_host_app.sh file? 

### ISSUE THREAD

**Issue by ahberg** [nwallace/passff#189]
Can't find it on https://github.com/nwallace/passff/releases

**Comment by nwallace** [comment]
That documentation was a placeholder -- a reminder to me to do that. If you just discovered the plugin, you can use the current version [here](https://addons.mozilla.org/en-US/firefox/addon/passff/) without need for the host app. But as we switch to Web Extensions, we'll need to get this in. If you want to use the build from Master, you'll have to install the host app manually for now.
