### ISSUE TITLE
Invisible text with dark KDE theme

### ISSUE THREAD

**Issue by davidar** [nwallace/passff#191]
When using a dark theme with firefox, passff currently looks like this (note the buttons at the lower left):

![spectacle z27751](https://cloud.githubusercontent.com/assets/24291/24854102/82c47aa8-1e20-11e7-8259-ebb5c13d6cc7.png)

**Comment by tuxor1337** [comment]
Would you please provide the name of the theme and a way how to install it?

**Comment by davidar** [comment]
I'm using the Breeze Dark system theme that comes with KDE5.

**Comment by tuxor1337** [comment]
Okay, that seems to be a KDE specific problem. I can't reproduce it with the dark GTK theme and I can't reproduce it by installing a dark Firefox Theme such as https://addons.mozilla.org/de/firefox/addon/breeze-dark/

One idea would be to explicitly mention dark font color in the popup CSS. For this, please add the line `color: #000;` after `div.buttonbox button {` (line 42) in https://github.com/nwallace/passff/blob/master/src/skin/popup.css#L42
