### ISSUE TITLE
Update installation docs for WebExtension release

### ISSUE THREAD

**Issue by josephholsten** [nwallace/passff#193]
Seems like the installation docs are really out of sync. Some things:

- "Download the install_host_app.sh script from our releases page and execute it." This link doesn't have any obvious candidates. I ended just wgeting src/host/install_host_app.sh
- The doc mentions a `passff.json` file, but no explanation is given about how that is installed
- The doc mentions a `passff.py` file, but no explanation is given about how that is installed

**Comment by tuxor1337** [comment]
As soon as there will be an official release for the WebExtension based version, the install script will be available from the releases page. Still, it's not clear whether this will identical with the file in `src/host/install_host_app.sh` since it currently requires to be executed from the directory `src/host/`.

Concerning `passff.json` and `passff.py`: You are right, we should probably give the complete paths `src/host/passff.py` and `src/host/passff.py`. But apart from that, the installation instructions seem to be pretty clear.

**Comment by josephholsten** [comment]
Would it make sense to add these installation instructions to a modal in the plugin, if it can't find the host app?

Does the version in the mozilla add-on page actually work with the latest firefox? Do I need to build from the repo to get things working?

**Comment by tuxor1337** [comment]
Graceful error handling for the case that the host app can't be accessed would be nice. If you or somebody else makes a pull request for this, we will be glad to accept.

For current versions of Firefox, the version on the mozilla add-on page should work.

**Comment by josephholsten** [comment]
grr, then I guess my setup is broken in some way. I'm really ready to move away from 1password, and this is my main blocker. I'll keep trying to put together an idiot-proof (read: works for the idiot who filed this ticket :-) set of install docs together.

I did notice that I ended up with an excessive number of hung `pass` processes before I gave up for the day. Is that related to any known issues/tickets?

**Comment by tuxor1337** [comment]
That's not an issue that I know of. But please make sure that it's caused by the current version from GitHub. There will be no fixes for the old version (from addons.mozilla.org).

**Comment by josephholsten** [comment]
ok, I'll make sure to use the current version. Is there a master ticket tracking what's left before the WebExtension version is released?

**Comment by tuxor1337** [comment]
So far, we have been discussing what's left to do in this issue: https://github.com/nwallace/passff/issues/169

But we're done (apart from the install script) and there has been little activity by the project maintainers @nwallace and @jvenant lately. It's mostly them who block this update at the moment, not any bugs that I know of.

**Comment by nwallace** [comment]
Yes, this issue will be resolved when we actually ship the new release. Let's direct any questions about that to the issue @tuxor1337 linked: #169
