### ISSUE TITLE
Icon not present on Firefox 53. Nor on 54 Developer addition without disabling then enabling

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [nwallace/passff#195]
Here's a log of me starting firefox 54, then disabling and enabling passff

https://pastebin.com/p6rFFH4Y

you can see the second try gets further and successfully creates the icon.

**Comment by tuxor1337** [comment]
We will drop support for this old version of the addon soon. The WebExtensions version now in Github is almost ready and waiting to be released.

**Comment by Ghoughpteighbteau** [comment]
we *will drop* support or we *have dropped* support? :P

Sorry if I missed a deprecation notice, I did my best to check everything for stuff like that.

What should I do as an alternative? Just wait... I guess?

**Comment by tuxor1337** [comment]
Yes, actually, nobody is working on the old version any longer ;)

You don't have to wait: Just use the latest code from Github (see the README for instructions) and you will probably be fine. The latest code is working. There are just some ongoing discussions about the installation instructions.
