### ISSUE TITLE
Button doesn't work when navigation bar is hidden.

### ISSUE THREAD

**Issue by facutuesca** [nwallace/passff#37]
If the navigation bar is hidden (with addons like "Hide Navigation Bar", "Toolbar Autohide", or "Pentadactyl"), and the button is moved to another place (like the tab bar, via right-click->customize), then clicking the button does not open the menu. If the nav bar is shown again, the button starts working again (even if it still is in the tab bar).
The easiest method I can find to reproduce this is:
1 - Move the Pass Manager button to the tab bar (here it still works)
2 - Install Pentadactyl: http://5digits.org/nightly/pentadactyl-latest.xpi
3 - Pentadactyl hides the nav bar by default, so now clicking the Pass button doesn't work anymore
4 - On Pentadactyl, type ":set guioptions+=mT" (without quotes) to show the nav bar
5 - The button works again

**Comment by leshy** [comment]
reporting the same issue with vimperator

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.

**Comment by akadaedalus** [comment]
Still a problem for me using Firefox 52.2 and Pentadactyl.
