### ISSUE TITLE
Rendering strangeness in Firefox 39

### ISSUE THREAD

**Issue by phipolis** [nwallace/passff#94]
Fedora Linux updated Firefox to 39 recently and I've been having weird rendering glitches with the passff plugin.

First, the list view in the passff main activity doesn't refresh automatically. When I first click the (P) icon, the view is empty. I must click 'refresh', close the view, and then click the (P) icon again. Now it shows the pattern match suggestions for the current site. If I double click a pass entry now visible in the list, nothing happens, the list stays the same. I must close the view and open it again for the ".., fill, fill and submit" menu to be visible. If I close the view a second time and click the (P) icon again, it goes back to the beginning with an empty view.

Second, it seems like all these rendered views are getting leaked. And the views get displayed one after another in submenus of the three-line menu button. The "History" and "Developer" menus are affected:
- If I haven't used pass yet, the menu is normal;
- If I've clicked (P) once, I will see most of the menu, with one instance of the pass view overlaid at the bottom;
- if I've clicked (P) multiple times, the menu is completely obscured and scrollable, I can scroll through the history of every version of the Pass view that's been rendered.

This happens even after creating a new profile, and it happens with passff as the only addon. Let me know if I can provide more information to help track this down. Using version 0.1.27, but this also happens in previous versions.

**Comment by phipolis** [comment]
Here are screenshots of the menu covering I described. The first is after restarting firefox and clicking the (P) icon once. My 10 recent pages were visible, but have been redacted. The second is after clicking the (P) icon a second time. Spooky.
![pass1](https://cloud.githubusercontent.com/assets/6742702/8897508/b1fdf0f6-33e4-11e5-8a00-d03715461a9f.jpg) ![pass2](https://cloud.githubusercontent.com/assets/6742702/8897512/bd1b4830-33e4-11e5-959a-1d9b34e29fad.jpg)

**Comment by jvenant** [comment]
I have no idea of where this behavior can come from.
It's Firefox who is in charge of displaying the ui....
Probably there is something wrong in the way I generate the interface. But I just can't figure out what it can be

**Comment by sometoby** [comment]
The entire interface code (and the overall project structure at that) is a bit antiquated. I am willing to bet that with some refactoring and rewriting according to https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials these weird rendering bugs will go away. Not only that, but our code may become more clear as well.

I'll experiment with modernizing things on a seperate branch.

**Comment by sometoby** [comment]
I've started integrating the old codebase into a newer project structure for Firefox addons. If anyone feels inclined to do so, you can check these changes out on the addon-sdk branch.

**Comment by josephholsten** [comment]
Anything we can do to help?

**Comment by sometoby** [comment]
Not directly, unless you have the time to familiarize yourself with the Addon SDK and feel like implementing some of the features that are still missing. Basic functionality for password filling works, but nothing much beyond that.

**Comment by sometoby** [comment]
My progress will be a bit slow too, I've been rather busy lately.

**Comment by jvenant** [comment]
I have no clue about what's going on with your Firefox UI. I can't reproduce this behaviour.
Probably as @sometoby suggest the best approach about this would by to redesign the interface.
But it is a huge refactoring. And like him, I rather busy at the moment

**Comment by sometoby** [comment]
It may also be worth mentioning that I've been experiencing this bug as well, but I've been unable to pinpoint the circumstances under which it occurs.

**Comment by Cadair** [comment]
I am also seeing this bug. Using Firefox 40 on arch linux.

**Comment by jvenant** [comment]
I've just had the behavior described in the first comment of @phipolis about the refresh issue (not the  menu covering).
In the browser console Firefox complain about : 
"the object cannot be linked to the inspector without a toolbox"
Didn't search deeper than googling the sentence, but there is a Firefox issue talking about that here
https://bugzilla.mozilla.org/show_bug.cgi?id=1166351

**Comment by josephholsten** [comment]
How's this coming along? I still get this issue, but it goes away with a restart. I'd love to help, but have no idea what I'm doing ;-)

**Comment by jvenant** [comment]
@sometoby works on a new version improving the ui of the plugin using the last firefox features. It's on the addon-sdk branch.
If you want to contribut, all pull requests are welcome ;)

**Comment by dllud** [comment]
+1
I'm also facing this issue, though it mostly happens during Private Browsing as in #109. In a Private Browsing window passFF does not render any new view. Restarting does not help. I wonder what's different between normal and private browsing to trigger this.
I'm on Lubuntu with Firefox 43.0.

**Comment by acabal** [comment]
I want to say this has been an issue for me too for a long time now, currently on FF 46.0.1 on Ubuntu 15.10.  Hoping to see this fixed soon :)

**Comment by tuxor1337** [comment]
It seems to me like you are beating a dead horse by implementing the whole thing based on the outdated Firefox extensions SDK (https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials). Instead you should look into WebExtensions (https://developer.mozilla.org/en-US/Add-ons/WebExtensions). There are several other browser extensions that try to combine `pass` with the WebExtensions framework. One is https://github.com/dannyvankooten/browserpass - maybe you can get inspiration from there?

Unfortunately, the native messaging API of WebExtensions requires the user to install a wrapper and a host manifest in addition to the Firefox extension itself: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging But that seems to be the future of browser extensions anyway...

**Comment by sometoby** [comment]
@tuxor1337 Sorry, but I've lost interest in PassFF and won't be contributing anymore.

**Comment by phipolis** [comment]
@tuxor1337 The official line is "we won't be migrating to Web Extensions any time soon" https://github.com/nwallace/passff/issues/169

**Comment by tuxor1337** [comment]
Just a crossref: https://github.com/nwallace/passff/issues/157#issuecomment-278012810

**Comment by tuxor1337** [comment]
Please reopen if this still applies to the latest version from Github.
